#토큰 만료기간: 기본 24시간(86400)을 48시간으로 변경한 코드
#oc describe oauth.config.openshift.io/cluster

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    accessTokenMaxAgeSeconds: 172800
